version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports: 
      - '3306:3306'
    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=sample-app
      - MYSQL_USER=Karl
      - MYSQL_PASSWORD=KlaraUkralaKlarnet